name: Python CI

# Trigger the workflow on any push to the main or pull request
on:
  push:
    branches: 
        - main
  pull_request:
    branches:
        - main

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            #Step-1)check out the code from repository

             - name: Check out code
               uses: actions/checkout@v2
        
            # Step-2) Set up Python Environment:
             - name: Set up Python Environment
               uses: actions/setup-python@v2
               with:
                python-version: '3.8'

            # Step-3) Install dependency
             - name: Install Dependency 
               run: 
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        
            # Step-4) Run Test
             - name: Run test
               run: pytest     








        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
